apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend  # 네임스페이스 추가
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: manji955/testback:7.0
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_IP
          value: mongodb.mongodb.svc.cluster.local  # 네임스페이스에 따른 서비스 참조 업데이트
        - name: MONGO_PORT
          value: "27017"
        volumeMounts:
        - mountPath: /usr/src/app    #/etc/localtime
          name: backend-claim0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
      volumes:
      - name: backend-claim0
        persistentVolumeClaim:
          claimName: backend-claim0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: backend  # 네임스페이스 추가
  labels:
    app: backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/backend-storage/b1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-claim0
  namespace: backend  # 네임스페이스 추가
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: backend  # 네임스페이스 추가
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP