apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend
spec:
  hard:
    pods: "5"
    requests.cpu: "800m"     #100m*5 + 여유CPU
    requests.memory: 800Mi   #100Mi*5 + 여유Memory
