apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend
spec:
  hard:
    pods: "10"
    requests.cpu: "1600m"    # 100m * 10 + 여유CPU
    requests.memory: 1.6Gi   # 100Mi * 10 + 여유Memory
